from pathlib import Path
root=Path('public')
def nav(active):
    links=''.join(f'<li class="nav-item"><a class="nav-link {"active" if name==active else ""} {"login-link" if name=="Login" else ""}" '+('aria-current="page" ' if name==active else '')+f'href="{url}">{name}</a></li>' for name,url in [('Home','index.html'),('About','about.html'),('Contact','contact.html'),('App','app.html'),('Login','login.html')])
    return '<nav class="navbar navbar-expand-md" aria-label="Main navigation"><div class="container"><a class="navbar-brand" href="index.html"><span class="brand-icon">L</span>Launchpad</a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav" aria-controls="mainNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="mainNav"><ul class="navbar-nav ms-auto">'+links+'</ul></div></div></nav>'
footer='<footer class="footer"><div class="container d-flex justify-content-between flex-wrap gap-2"><span>Launchpad / A place to start.</span><span>Sean Farmer · CS651 · Part 1</span></div></footer>'
def page(name,file,body,script='static'):
    html=f'<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Launchpad: a flexible workspace for ideas, plans, and learning."><title>{name} | Launchpad</title><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/bootstrap.min.css"><link rel="stylesheet" href="styles.css"></head><body>{body}<script src="assets/{script}.js" defer></script></body></html>'
    (root/file).write_text(html)
image='<img class="hero-image" src="images/workspace.svg" alt="A connected workflow: capture a fresh idea, organize a plan, and see your progress">'
page('Home','index.html',nav('Home')+f'<main><section class="container hero"><div class="row align-items-center g-5"><div class="col-lg-6"><div class="eyebrow">Space to think. Room to grow.</div><h1>Good things start<br>with a little space.</h1><p class="lead">Meet Launchpad. A simple workspace for your ideas, your plans, and whatever comes next.</p><div class="d-flex gap-3 flex-wrap mt-4"><a class="btn btn-primary" href="app.html">Open workspace</a><a class="btn btn-outline-primary" href="about.html">Get to know us</a></div></div><div class="col-lg-6">{image}</div></div></section><section class="container section"><div class="d-flex justify-content-between align-items-center mb-4"><h2>A starting point, not a limit.</h2></div><div class="row g-4">'+''.join(f'<div class="col-md-4"><article class="panel h-100"><div class="feature-number">0{i} / {tag}</div><h3>{title}</h3><p class="muted mb-0">{desc}</p></article></div>' for i,tag,title,desc in [(1,'EXPLORE','Find a little inspiration.','Browse starting points for planning, creativity, and learning.'),(2,'MAKE IT YOURS','Keep what matters.','Save the ideas you like to your own workspace view.'),(3,'MOVE FORWARD','Take the next small step.','Try the getting-started checklist and watch your progress grow.')])+'</div></section></main>'+footer)
page('About','about.html',nav('About')+f'<main class="container"><section class="hero"><div class="row align-items-center g-5"><div class="col-lg-6"><div class="eyebrow">About Launchpad</div><h1>Start simple.<br>Make room for more.</h1><p class="lead">You don’t need every answer before you begin. Sometimes, you just need somewhere to put the first idea.</p><p class="muted">Launchpad is an early workspace concept by Sean Farmer, created for CS651. It brings a few useful starting points into one calm, approachable space.</p><p class="muted">Explore a card, save an idea, and make a little progress. The workspace is a starting point that will grow as its purpose takes shape.</p><a class="btn btn-primary mt-2" href="app.html">Explore the workspace</a></div><div class="col-lg-6">{image}</div></div></section><section class="section"><div class="row g-4"><div class="col-md-6"><div class="panel h-100"><h3>Simple by design</h3><p class="muted mb-0">Clear navigation and familiar controls keep the focus on what you want to do.</p></div></div><div class="col-md-6"><div class="panel h-100"><h3>Room to evolve</h3><p class="muted mb-0">A flexible foundation means new ideas can find their place as the project develops.</p></div></div></div></section></main>'+footer)
page('Contact','contact.html',nav('Contact')+f'<main class="container"><section class="hero"><div class="row align-items-center g-5"><div class="col-lg-6"><div class="eyebrow">Contact</div><h1>Every good idea<br>starts a conversation.</h1><p class="lead">Have a thought about Launchpad? Feedback on what feels useful—or what could be clearer—is welcome.</p><div class="panel mt-4"><div class="eyebrow mb-2">Project contact</div><h3>Sean Farmer</h3><p class="muted mb-3">CS651 · California State University, East Bay</p><p class="mb-0">For class-related feedback, contact Sean through the course’s Canvas messaging system.</p></div><p class="app-note mt-3">This demo does not collect or send messages.</p></div><div class="col-lg-6">{image}</div></div></section></main>'+footer)
page('Workspace','app.html','<div id="root"></div>','workspace')
page('Sign in','login.html','<div id="root"></div>','login')
